on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
     
      - name: 'login to docker'
        run: docker login --username ${{ secrets.USERNAME1 }} --password ${{ secrets.PASSWORD1 }}
      - name: 'building image'
        run: docker build -t ${{ secrets.USERNAME1 }}/imagetask .
        
      - name: 'pushing to docker hup'
        run: docker push ${{ secrets.USERNAME1 }}/imagetask
