on:
  push:
    branches: newbranch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
     
      - name: 'login to docker'
        run: docker login --username ${{ USERNAME1 }} --password ${{ PASSWORD1 }}
      - name: 'building image'
        run: docker build -t ${{ USERNAME1 }}/imagetask .
        
      - name: 'pushing to docker hup'
        run: docker push ${{ USERNAME1 }}/imagetask
